export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",    
  LOGOUT_REQUEST: "LOGOUT_REQUEST" ,
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE", 
}

export const appConstants = {
  GET_STREAMS_REQUEST: "GET_STREAMS_REQUEST",
  GET_STREAMS_SUCCESS: "GET_STREAMS_SUCCESS",
  GET_STREAMS_FAILURE: "GET_STREAMS_FAILURE",
  GET_MY_STREAMS_REQUEST: "GET_MY_STREAMS_REQUEST",
  GET_MY_STREAMS_SUCCESS: "GET_MY_STREAMS_SUCCESS",
  GET_MY_STREAMS_FAILURE: "GET_MY_STREAMS_FAILURE"
}